FROM osrf/ros:jazzy-desktop

# Unico blocco RUN per ottimizzare i layer dell'immagine
RUN apt-get update -y && apt-get install -y \
    nano \
    iputils-ping \
    python3-pip \
    wget \
    ros-jazzy-ros-gz \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-ros-gz-sim \
    ros-jazzy-ros-gz-interfaces \
    ros-jazzy-xacro \
    ros-jazzy-joint-state-publisher-gui \
    ros-jazzy-urdf-tutorial \
    liburdfdom-tools \
    && rm -rf /var/lib/apt/lists/*
